/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue.ajout;

import be.isfce.tfe.controleur.ChauffeurControleur;
import be.isfce.tfe.controleur.ValidationException;
import be.isfce.tfe.metier.Chauffeur;
import javax.swing.JOptionPane;

/**
 *
 * @author yema
 */
public class AjoutChauffeurJPanell extends javax.swing.JPanel {

    private DialogUtils.DialogInterface dialogInterface;

    /**
     * Creates new form EncodageChauffeurJPanell
     */
    public AjoutChauffeurJPanell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enregistrerChauffeur = new javax.swing.JButton();
        ajoutChauffeurJPanell1 = new be.isfce.tfe.vue.encodage.EncodageChauffeurJPanell();

        enregistrerChauffeur.setText("Enregistrer");
        enregistrerChauffeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerChauffeurActionPerformed(evt);
            }
        });

        ajoutChauffeurJPanell1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chauffeur"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajoutChauffeurJPanell1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(enregistrerChauffeur, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajoutChauffeurJPanell1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enregistrerChauffeur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //Permet de savoir quand la dialog à été fermée.
    public void setDialogInterface(DialogUtils.DialogInterface dialogInterface) {
        this.dialogInterface = dialogInterface;
    }
    //Quand le bouton enregistrer est cliqué.
    private void enregistrerChauffeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerChauffeurActionPerformed
        //Récupère le chauffeur depuis les champs d'entrée.
        Chauffeur chauffeur = ajoutChauffeurJPanell1.getChauffeurFromFields();
        try {
            //L'ajoute dans la base de donnée.
            new ChauffeurControleur().controleEtAjoute(chauffeur);
            dialogInterface.onButtonSavePressed();
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enregistrerChauffeurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private be.isfce.tfe.vue.encodage.EncodageChauffeurJPanell ajoutChauffeurJPanell1;
    private javax.swing.JButton enregistrerChauffeur;
    // End of variables declaration//GEN-END:variables
}
