/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue.ajout;

import be.isfce.tfe.controleur.ChauffeurControleur;
import be.isfce.tfe.controleur.MaterielRoulantControleur;
import be.isfce.tfe.controleur.ValidationException;
import be.isfce.tfe.db.ChauffeurDBHelper;
import be.isfce.tfe.db.MaterielRoulantDBHelper;
import be.isfce.tfe.metier.MaterielRoulant;
import be.isfce.tfe.modele.MaterielRoulantModele;
import be.isfce.tfe.validation.StringValidation;
import be.isfce.tfe.validation.ValidationPlaque;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author yema
 */
public class AjoutMateielRoulantJPanell extends javax.swing.JPanel {

    /**
     * Creates new form AjoutMateielRoulantJPanell
     */
    public AjoutMateielRoulantJPanell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idvehicule = new javax.swing.JLabel();
        marquevehicule = new javax.swing.JLabel();
        typevehicule = new javax.swing.JLabel();
        numimmatr = new javax.swing.JLabel();
        carburant = new javax.swing.JLabel();
        nbplaces = new javax.swing.JLabel();
        identifiantTextField = new javax.swing.JTextField();
        marqueTextField = new javax.swing.JTextField();
        typeTextField = new javax.swing.JTextField();
        plaqueTextField = new javax.swing.JTextField();
        carburantTextField = new javax.swing.JTextField();
        nbdeplaceTextField = new javax.swing.JTextField();
        ajoutervehicule = new javax.swing.JToggleButton();
        modifiervehicule = new javax.swing.JToggleButton();
        supprimervehicule = new javax.swing.JToggleButton();
        kilometrage = new javax.swing.JLabel();
        kilometrageTextField = new javax.swing.JTextField();
        anneedeconstructionjllabel = new javax.swing.JLabel();
        datevaliterextincteur = new javax.swing.JLabel();
        validiterexctincteur = new com.toedter.calendar.JDateChooser();
        anneeconstruction = new com.toedter.calendar.JDateChooser();

        idvehicule.setText("Numero de chassis:");

        marquevehicule.setText("Marque:");

        typevehicule.setText("Type:");

        numimmatr.setText("Plaque immatriculation:");

        carburant.setText("Carburant:");

        nbplaces.setText("Nombres de Places:");

        marqueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marqueTextFieldActionPerformed(evt);
            }
        });

        plaqueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plaqueTextFieldActionPerformed(evt);
            }
        });

        ajoutervehicule.setText("Enregistrer");
        ajoutervehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutervehiculeActionPerformed(evt);
            }
        });

        modifiervehicule.setText("Reset");
        modifiervehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifiervehiculeActionPerformed(evt);
            }
        });

        supprimervehicule.setText("Annuler");

        kilometrage.setText("Kilometrage:");

        anneedeconstructionjllabel.setText("Annee de construction:");

        datevaliterextincteur.setText("Date validiter exctincteur:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ajoutervehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modifiervehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(supprimervehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(datevaliterextincteur)
                        .addGap(18, 18, 18)
                        .addComponent(validiterexctincteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typevehicule)
                            .addComponent(anneedeconstructionjllabel)
                            .addComponent(carburant)
                            .addComponent(nbplaces)
                            .addComponent(kilometrage, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numimmatr))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(plaqueTextField)
                            .addComponent(carburantTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nbdeplaceTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kilometrageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(anneeconstruction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marquevehicule)
                            .addComponent(idvehicule))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marqueTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(identifiantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idvehicule)
                    .addComponent(identifiantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marquevehicule)
                    .addComponent(marqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typevehicule)
                    .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anneedeconstructionjllabel)
                    .addComponent(anneeconstruction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numimmatr)
                            .addComponent(plaqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carburant)
                            .addComponent(carburantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nbplaces)
                            .addComponent(nbdeplaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kilometrage)
                            .addComponent(kilometrageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(datevaliterextincteur))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(validiterexctincteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajoutervehicule)
                    .addComponent(modifiervehicule)
                    .addComponent(supprimervehicule))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modifiervehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifiervehiculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifiervehiculeActionPerformed

    private void marqueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marqueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marqueTextFieldActionPerformed

    private void plaqueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plaqueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plaqueTextFieldActionPerformed

    private void ajoutervehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutervehiculeActionPerformed
        // TODO add your handling code here:
        MaterielRoulant materielroulant = getMaterielRoulantFromFields();
        try {
            new MaterielRoulantControleur(MaterielRoulantModele.getInstance()).controleEtAjoute(materielroulant);
           
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ajoutervehiculeActionPerformed

    private MaterielRoulant getMaterielRoulantFromFields() {
        MaterielRoulant materielroulant = new MaterielRoulant();
        materielroulant.setId(identifiantTextField.getText());

        materielroulant.setMarque(marqueTextField.getText());

        materielroulant.setType(typeTextField.getText());

        materielroulant.setAnneedeconstruction(anneeconstruction.getDate());

        String plaque = plaqueTextField.getText();
        ValidationPlaque.checkPlaque(plaque);
        plaque = plaque.replace(".", "");
        plaque = plaque.replace("-", "");
        materielroulant.setNumImmatr(plaque);

        materielroulant.setCarburant(carburantTextField.getText());

        try {
            materielroulant.setNbDePlaces(Integer.valueOf(nbdeplaceTextField.getText()));
        } catch (NumberFormatException e) {
            materielroulant.setNbDePlaces(0);
        }
        try {
            materielroulant.setKmactuel(Integer.valueOf(kilometrageTextField.getText()));
        } catch (NumberFormatException e) {
            materielroulant.setNbDePlaces(0);
        }

        materielroulant.setDateexctincteur(validiterexctincteur.getDate());
        return materielroulant;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ajoutervehicule;
    private com.toedter.calendar.JDateChooser anneeconstruction;
    private javax.swing.JLabel anneedeconstructionjllabel;
    private javax.swing.JLabel carburant;
    private javax.swing.JTextField carburantTextField;
    private javax.swing.JLabel datevaliterextincteur;
    private javax.swing.JTextField identifiantTextField;
    private javax.swing.JLabel idvehicule;
    private javax.swing.JLabel kilometrage;
    private javax.swing.JTextField kilometrageTextField;
    private javax.swing.JTextField marqueTextField;
    private javax.swing.JLabel marquevehicule;
    private javax.swing.JToggleButton modifiervehicule;
    private javax.swing.JTextField nbdeplaceTextField;
    private javax.swing.JLabel nbplaces;
    private javax.swing.JLabel numimmatr;
    private javax.swing.JTextField plaqueTextField;
    private javax.swing.JToggleButton supprimervehicule;
    private javax.swing.JTextField typeTextField;
    private javax.swing.JLabel typevehicule;
    private com.toedter.calendar.JDateChooser validiterexctincteur;
    // End of variables declaration//GEN-END:variables
}
