/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue.ajout;

import be.isfce.tfe.controleur.TrajetsControleur;
import be.isfce.tfe.controleur.ValidationException;
import be.isfce.tfe.metier.Trajet;
import javax.swing.JOptionPane;

/**
 *
 * @author yema
 */
public class AjoutTrajetsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsertionHeuredetravailJPanel1
     */
    public AjoutTrajetsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enregistrerheuredetravail = new javax.swing.JButton();
        ajoutTrajetsJPanel1 = new be.isfce.tfe.vue.encodage.EncodageTrajetsJPanel();

        enregistrerheuredetravail.setText("Enregistrer");
        enregistrerheuredetravail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerheuredetravailActionPerformed(evt);
            }
        });

        ajoutTrajetsJPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Durée du Parcours"));
        ajoutTrajetsJPanel1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enregistrerheuredetravail)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajoutTrajetsJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajoutTrajetsJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enregistrerheuredetravail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerheuredetravailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerheuredetravailActionPerformed
        // TODO add your handling code here:
        Trajet trajet = ajoutTrajetsJPanel1.getTrajetFromFields();
        try {
            new TrajetsControleur().controleEtAjoute(trajet);
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enregistrerheuredetravailActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private be.isfce.tfe.vue.encodage.EncodageTrajetsJPanel ajoutTrajetsJPanel1;
    private javax.swing.JButton enregistrerheuredetravail;
    // End of variables declaration//GEN-END:variables
}
