/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue.affichage;

import be.isfce.tfe.controleur.AbstractControleur;
import be.isfce.tfe.metier.Chauffeur;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Observer;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author yema
 */
public abstract class AffichagePanel<T> extends javax.swing.JPanel implements Observer {

    private JPopupMenu popupMenu;

    protected AbstractControleur<T> abstractControleur;

    /**
     * Creates new form AffichagePanel
     *
     * @param abstractControleur
     */
    public AffichagePanel(AbstractControleur<T> abstractControleur) {
        initComponents();
        this.abstractControleur = abstractControleur;
        this.abstractControleur.getModele().addObserver(this);
        setBorder(javax.swing.BorderFactory.createTitledBorder(getTitrePanel()));
        popupMenu = new JPopupMenu();
        JMenuItem deleteItem = new JMenuItem("Supprimer");
        deleteItem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                supprimeElement(jTable1.getSelectedRow());
            }

        });
        popupMenu.add(deleteItem);
        List<JMenuItem> menuItems = getMenuItems();
        for (JMenuItem menuItem : menuItems) {
            popupMenu.add(menuItem);
        }
        jTable1.addMouseListener(new MouseAdapter() {

            public void mouseReleased(MouseEvent e) {
                int row = jTable1.rowAtPoint(e.getPoint());
                int column = jTable1.columnAtPoint(e.getPoint());

                if (!jTable1.isRowSelected(row)) {
                    jTable1.changeSelection(row, column, false, false);
                }

                popupMenu.show(e.getComponent(), e.getX(), e.getY());

            }
        });
    }

    protected void displayData() {
        jTable1.setModel(getTableModel());
    }

    public abstract AbstractTableModel getTableModel();

    public abstract String getTitrePanel();

    protected abstract void supprimeElement(int index);

    protected abstract List<JMenuItem> getMenuItems();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
