/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue.encodage;

import be.isfce.tfe.db.CarteCarburantDao;
import be.isfce.tfe.db.ChauffeurDao;
import be.isfce.tfe.db.MaterielRoulantDao;
import be.isfce.tfe.metier.CarteCarburant;
import be.isfce.tfe.metier.Chauffeur;
import be.isfce.tfe.metier.MaterielRoulant;
import be.isfce.tfe.metier.UtilisationCarte;
import java.util.List;

/**
 *
 * @author yema
 */
public class EncodageUtilisationCarteJPanell extends javax.swing.JPanel {

    /**
     * Creates new form AjoutUtilisationCarteJPanell
     */
    List<CarteCarburant> cartes;
    List<Chauffeur> chauffeurs;

    public EncodageUtilisationCarteJPanell() {
        initComponents();
        initCombo();
    }

    private void initCombo() {
        cartes = CarteCarburantDao.getTousLesCartesCarburant();
        for (CarteCarburant carte : cartes) {
            jComboBox1.addItem(carte.getNumcarte());
        }
        chauffeurs = ChauffeurDao.getTousLesChauffeurs();
        for (Chauffeur chauffeur : chauffeurs) {
            jComboBoxChauffeur.addItem(chauffeur.getNomChauffeur() + " " + chauffeur.getPrenomChauffeur());
        }
    }

    public UtilisationCarte getUtilisationFromFields() {
        UtilisationCarte carte = new UtilisationCarte();
        carte.setIdutilisationcarte(0);
        carte.setDateutilisation(dateutilisation.getDate());
        carte.setLitrecarburant(Integer.valueOf(litredieselTextField.getText()));
        carte.setKmutilisation(Integer.valueOf(kmutilisationTextField.getText()));
        carte.setIdcartecarburant(cartes.get(jComboBox1.getSelectedIndex()).getId());
        carte.setIdchauffeur(chauffeurs.get(jComboBoxChauffeur.getSelectedIndex()).getId());
        return carte;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateutilisation = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        litredieselTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kmutilisationTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxChauffeur = new javax.swing.JComboBox();

        jLabel1.setText("Date utilisation :");

        jLabel2.setText("Numéro de Carte  :");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Litre de carburant:");

        jLabel4.setText("kilométre utilisation:");

        jLabel5.setText("Chauffeur");

        jComboBoxChauffeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChauffeurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(litredieselTextField)
                            .addComponent(kmutilisationTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(dateutilisation, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxChauffeur, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateutilisation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(litredieselTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kmutilisationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxChauffeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBoxChauffeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChauffeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxChauffeurActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateutilisation;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxChauffeur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField kmutilisationTextField;
    private javax.swing.JTextField litredieselTextField;
    // End of variables declaration//GEN-END:variables
}
