/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue.encodage;

import be.isfce.tfe.vue.ajout.*;
import be.isfce.tfe.controleur.MaterielRoulantControleur;
import be.isfce.tfe.controleur.ValidationException;
import be.isfce.tfe.db.TypeMaterielDao;
import be.isfce.tfe.metier.MaterielRoulant;
import be.isfce.tfe.metier.TypeMaterielRoulant;
import be.isfce.tfe.validation.ValidationPlaque;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author yema
 */
public class EncodageMaterielRoulantJPanell extends javax.swing.JPanel {

     List<TypeMaterielRoulant> types;

  
       
    

     
    public EncodageMaterielRoulantJPanell() {
          initComponents();
          types = TypeMaterielDao.getTousLesTypesMateriel();
          initComboboxType();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idvehicule = new javax.swing.JLabel();
        marquevehicule = new javax.swing.JLabel();
        numimmatr = new javax.swing.JLabel();
        carburant = new javax.swing.JLabel();
        nbplaces = new javax.swing.JLabel();
        identifiantTextField = new javax.swing.JTextField();
        marqueTextField = new javax.swing.JTextField();
        plaqueTextField = new javax.swing.JTextField();
        carburantTextField = new javax.swing.JTextField();
        nbdeplaceTextField = new javax.swing.JTextField();
        kilometrage = new javax.swing.JLabel();
        kilometrageTextField = new javax.swing.JTextField();
        anneedeconstructionjllabel = new javax.swing.JLabel();
        datevaliterextincteur = new javax.swing.JLabel();
        validiterexctincteur = new com.toedter.calendar.JDateChooser();
        anneeconstruction = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        typematerielComboBox = new javax.swing.JComboBox();

        idvehicule.setText("Numero de chassis:");

        marquevehicule.setText("Marque:");

        numimmatr.setText("Plaque immatriculation:");

        carburant.setText("Carburant:");

        nbplaces.setText("Nombres de Places:");

        marqueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marqueTextFieldActionPerformed(evt);
            }
        });

        plaqueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plaqueTextFieldActionPerformed(evt);
            }
        });

        kilometrage.setText("Kilometrage:");

        anneedeconstructionjllabel.setText("Annee de construction:");

        datevaliterextincteur.setText("Date validité exctincteur:");

        jLabel1.setText("type:");

        typematerielComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typematerielComboBoxItemStateChanged(evt);
            }
        });
        typematerielComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typematerielComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marquevehicule)
                            .addComponent(idvehicule))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marqueTextField)
                            .addComponent(identifiantTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anneedeconstructionjllabel)
                        .addGap(27, 27, 27)
                        .addComponent(anneeconstruction, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(datevaliterextincteur)
                        .addGap(18, 18, 18)
                        .addComponent(validiterexctincteur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kilometrage, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(kilometrageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nbplaces)
                        .addGap(45, 45, 45)
                        .addComponent(nbdeplaceTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(carburant)
                        .addGap(86, 86, 86)
                        .addComponent(carburantTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numimmatr)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plaqueTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typematerielComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idvehicule)
                    .addComponent(identifiantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marquevehicule)
                    .addComponent(marqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anneedeconstructionjllabel)
                    .addComponent(anneeconstruction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typematerielComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numimmatr, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(plaqueTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(carburant)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(carburantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nbplaces, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nbdeplaceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kilometrage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kilometrageTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datevaliterextincteur, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(validiterexctincteur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void marqueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marqueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marqueTextFieldActionPerformed

    private void plaqueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plaqueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plaqueTextFieldActionPerformed

    private void typematerielComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typematerielComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typematerielComboBoxActionPerformed

    private void typematerielComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typematerielComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_typematerielComboBoxItemStateChanged

    public MaterielRoulant getMaterielRoulantFromFields() {
        MaterielRoulant materielroulant = new MaterielRoulant();
        materielroulant.setId(identifiantTextField.getText());

        materielroulant.setMarque(marqueTextField.getText());
        
        materielroulant.setIdtypemateriel( types.get(typematerielComboBox.getSelectedIndex()).getIdtypemateriel());

      
        materielroulant.setAnneedeconstruction(anneeconstruction.getDate());

        String plaque = plaqueTextField.getText();
        ValidationPlaque.checkPlaque(plaque);
        plaque = plaque.replace(".", "");
        plaque = plaque.replace("-", "");
        materielroulant.setNumImmatr(plaque);

        materielroulant.setCarburant(carburantTextField.getText());

        try {
            materielroulant.setNbDePlaces(Integer.valueOf(nbdeplaceTextField.getText()));
        } catch (NumberFormatException e) {
            materielroulant.setNbDePlaces(0);
        }
        try {
            materielroulant.setKmactuel(Integer.valueOf(kilometrageTextField.getText()));
        } catch (NumberFormatException e) {
            materielroulant.setNbDePlaces(0);
        }

        materielroulant.setDateexctincteur(validiterexctincteur.getDate());
        return materielroulant;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser anneeconstruction;
    private javax.swing.JLabel anneedeconstructionjllabel;
    private javax.swing.JLabel carburant;
    private javax.swing.JTextField carburantTextField;
    private javax.swing.JLabel datevaliterextincteur;
    private javax.swing.JTextField identifiantTextField;
    private javax.swing.JLabel idvehicule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kilometrage;
    private javax.swing.JTextField kilometrageTextField;
    private javax.swing.JTextField marqueTextField;
    private javax.swing.JLabel marquevehicule;
    private javax.swing.JTextField nbdeplaceTextField;
    private javax.swing.JLabel nbplaces;
    private javax.swing.JLabel numimmatr;
    private javax.swing.JTextField plaqueTextField;
    private javax.swing.JComboBox typematerielComboBox;
    private com.toedter.calendar.JDateChooser validiterexctincteur;
    // End of variables declaration//GEN-END:variables
private void initComboboxType() {
        for (TypeMaterielRoulant typemateriel : types) {
            typematerielComboBox.addItem(typemateriel.getTypemateriel());
        }
    }

}

