/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue.frame.tabs;

import be.isfce.tfe.controleur.CarteCarburantControleur;
import be.isfce.tfe.controleur.EcoleControlleur;
import be.isfce.tfe.db.CarteCarburantDao;
import be.isfce.tfe.db.EcoleDao;
import be.isfce.tfe.vue.affichage.AffichageCarteCarburantPanel;
import be.isfce.tfe.vue.affichage.AffichageEcolePanel;
import be.isfce.tfe.vue.ajout.AjoutCarteCarburantJPanell;
import be.isfce.tfe.vue.ajout.DialogUtils;
import java.awt.BorderLayout;
import javax.swing.JDialog;

/**
 *
 * @author serro_000
 */
public class CarteCarburantTabPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChauffeurTabPanel
     */
    public CarteCarburantTabPanel() {
        initComponents();
        affichageCarteCarburantPanel = new AffichageCarteCarburantPanel(new CarteCarburantControleur(), CarteCarburantDao.getTousLesCartesCarburant());
        jPanel1.add(affichageCarteCarburantPanel, BorderLayout.CENTER);
    }

    public void refresh(){
        affichageCarteCarburantPanel.setCarteCarburant(CarteCarburantDao.getTousLesCartesCarburant());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jButton1.setText("Ajouter une carte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 356, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       AjoutCarteCarburantJPanell ajoutCarteJPanell = new AjoutCarteCarburantJPanell();
        ajoutCarteJPanell.setDialogInterface(new DialogUtils.DialogInterface() {

            @Override
            public void onButtonSavePressed() {
                if (jDialog != null) {
                    jDialog.dispose();
                    affichageCarteCarburantPanel.setCarteCarburant(CarteCarburantDao.getTousLesCartesCarburant());
                }
            }
        });
        jDialog = DialogUtils.afficheDialog(null, ajoutCarteJPanell);  
    }//GEN-LAST:event_jButton1ActionPerformed

 private JDialog jDialog;
    private final AffichageCarteCarburantPanel affichageCarteCarburantPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
