/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue.frame.tabs;

import be.isfce.tfe.controleur.ChauffeurControleur;
import be.isfce.tfe.db.ChauffeurDao;
import be.isfce.tfe.metier.Chauffeur;
import be.isfce.tfe.vue.affichage.AffichageChauffeurPanel;
import be.isfce.tfe.vue.ajout.AjoutChauffeurJPanell;
import be.isfce.tfe.vue.ajout.DialogUtils;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;

/**
 *
 * @author serro_000
 */
public class ChauffeurTabPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChauffeurTabPanel
     */
    public ChauffeurTabPanel() {
        initComponents();
        affichageChauffeurPanel = new AffichageChauffeurPanel(new ChauffeurControleur(), ChauffeurDao.getTousLesChauffeurs());
        jPanel1.add(affichageChauffeurPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("Ajouter un chauffeur");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jCheckBox1.setText("Afficher chauffeurs archivés");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jTextField1.setToolTipText("");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel1.setText("Recherche");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jCheckBox1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Crée un Panel d'ajout de chauffeur
        AjoutChauffeurJPanell ajoutChauffeurJPanell = new AjoutChauffeurJPanell();
        //On le lie à un DialogInterface pour savoir quand la Dialog disparait.
        ajoutChauffeurJPanell.setDialogInterface(new DialogUtils.DialogInterface() {

            @Override
            public void onButtonSavePressed() {
                if (jDialog != null) {
                    jDialog.dispose();
                    //Quand le boutton enregistrer est cliqué, on recharche les chauffeurs
                    affichageChauffeurPanel.setChauffeurs(ChauffeurDao.getTousLesChauffeurs());
                }
            }
        });
        jDialog = DialogUtils.afficheDialog(null, ajoutChauffeurJPanell);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // Permet de filtrer les chauffeur archivé
        // Si le checkbox est selectionnée, on affiche les archives
        boolean selected = jCheckBox1.isSelected();
        if (selected) {
            affichageChauffeurPanel.setChauffeurs(ChauffeurDao.getTousLesChauffeursarchives());
        } else {
            affichageChauffeurPanel.setChauffeurs(ChauffeurDao.getTousLesChauffeurs());
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        List<Chauffeur> tousLesChauffeurs = jCheckBox1.isSelected() ? ChauffeurDao.getTousLesChauffeursarchives() : ChauffeurDao.getTousLesChauffeurs();
        List<Chauffeur> chauffeurTrouvés = new ArrayList<Chauffeur>();
        String idAChercher = jTextField1.getText();
        if (idAChercher.isEmpty()) {
            affichageChauffeurPanel.setChauffeurs(tousLesChauffeurs);
        } else {
            for (Chauffeur chauffeur : tousLesChauffeurs) {
                if (chauffeur.getId().toLowerCase().contains(idAChercher.toLowerCase())) {
                    chauffeurTrouvés.add(chauffeur);
                }
            }
            affichageChauffeurPanel.setChauffeurs(chauffeurTrouvés);
        }
    }//GEN-LAST:event_jTextField1KeyReleased
    private JDialog jDialog;
    private final AffichageChauffeurPanel affichageChauffeurPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
