/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue.frame.tabs;

import be.isfce.tfe.controleur.ChauffeurControleur;
import be.isfce.tfe.controleur.MaterielRoulantControleur;
import be.isfce.tfe.db.ChauffeurDao;
import be.isfce.tfe.db.MaterielRoulantDao;
import be.isfce.tfe.vue.affichage.AffichageChauffeurPanel;
import be.isfce.tfe.vue.affichage.AffichageMaterielRoulantPanel;
import be.isfce.tfe.vue.affichage.AfficherEtRechercherAmendePanel;
import be.isfce.tfe.vue.affichage.AfficherEtRechercherEntretienPanel;
import be.isfce.tfe.vue.ajout.AjoutMaterielRoulantJPanell;
import be.isfce.tfe.vue.ajout.DialogUtils;
import java.awt.BorderLayout;
import javax.swing.JDialog;

/**
 *
 * @author serro_000
 */
public class VehiculeTabPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChauffeurTabPanel
     */
    public VehiculeTabPanel() {
        initComponents();
        affichageVehiculePanel = new AffichageMaterielRoulantPanel(new MaterielRoulantControleur(), MaterielRoulantDao.getTousLesVehicules());
        jPanel1.add(affichageVehiculePanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("Ajouter un véhicule");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton2.setText("Chercher un entretien");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("chercher Amende par date");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AjoutMaterielRoulantJPanell ajoutVehiculeJPanell = new AjoutMaterielRoulantJPanell();
        ajoutVehiculeJPanell.setDialogInterface(new DialogUtils.DialogInterface() {

            @Override
            public void onButtonSavePressed() {
                if (jDialog != null) {
                    jDialog.dispose();
                    affichageVehiculePanel.setVehicules(MaterielRoulantDao.getTousLesVehicules());
                }
            }
        });
        jDialog = DialogUtils.afficheDialog(null, ajoutVehiculeJPanell);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DialogUtils.afficheDialog(null, new AfficherEtRechercherEntretienPanel());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         DialogUtils.afficheDialog(null, new AfficherEtRechercherAmendePanel());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private JDialog jDialog;
    private final AffichageMaterielRoulantPanel affichageVehiculePanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
